config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'static_pages/about'

  resources :users do
    resources :games
  end

#  resources :games
#  resources :users

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html


  root 'users#index'


end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :games
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  before_action :user_needs_name, only: [:show]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
    @users_w_game_counts = User.select("users.*, COUNT(games.id) as games_count").joins("LEFT OUTER JOIN games ON (games.user_id = users.id)")
    .where("games.outcome = 1 AND users.name <> ''")
    .group("users.id")
    .order("games_count DESC")
    .limit(10)
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])

    # Look at the games the user played
    @user_games = @user.games.where(outcome: [0, 1]).order(created_at: :desc)
    @user_wins = @user.games.where("outcome = 1")

    @user_games_count = @user_games.length
    @user_wins_count = @user_wins.length
    if @user_games_count > 0
      @user_success_ratio = (( @user_wins_count * 1.00) / @user_games_count * 100).round()
    else
      @user_success_ratio = 0
    end

    # Has user played all words available?
    @all_words = Word.pluck(:word)
    @user_games_words = @user.games.pluck(:secret_word)
    @all_words.each { |w|
      if !( @user_games_words.include? w )
        @user_has_more_words_to_play = 1
        break
      end
    }
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
    redirect_to(root_url) unless @user == current_user
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :email)
    end

    def user_needs_name
      redirect_to(edit_user_path(current_user)) if current_user.name.blank?
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for(user) do |f| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div>

  <div class="actions">
    <%= f.submit "Update User", class: "btn btn-success" %>
  </div>
<% end %>

app/views/users/edit.html.erb
<div class="row">
  <div class="col-sm-8 col-sm-offset-2">
    <div class="well text-center">
      <h1>Edit your profile details</h1>

      <% if @user.name.blank? %>
        <h3 id="missing-user-name-alert">Please enter your name</h3>
      <% end %>

      <%= render 'form', user: @user %>

      <%= link_to 'Back to profile', @user %>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<div class="row">
  <div class="col-sm-8 col-sm-offset-2">
    <div class="well">
      <div id="leaderboard" class="text-center">
        <h1>TOP 10</h1>
        <table>
          <thead>
            <tr>
              <th>PLAYER</th>
              <th>WINS</th>
            </tr>
          </thead>

          <tbody>
            <% @users_w_game_counts.each do |user| %>
              <tr>
                <td><%= link_to user.name, user %></td>
                <td><%= user.games_count %></td>
              </tr>
            <% end %>
          </tbody>
        </table>

        <hr>
        <%= link_to "New Game", new_user_game_path(user_id: current_user.id), class: "btn btn-success" if user_signed_in? %>
      </div>
    </div>
  </div>
</div>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<div class="row">
  <div class="col-sm-8 col-sm-offset-2">
    <h1 class="text-center profile-greeting">
      <% if @user == current_user %>
      Hello, <%= @user.name %>!
      <% else %>
        <%= @user.name %>'s profile
      <% end %>
    </h1>
    <% if @user_games_count > 0 %>
      <div id="profile-stats" class="well text-center">
          <h2>Game Stats</h2>
          <% if (@user == current_user) && (@user_has_more_words_to_play.blank?) %>
            <h3>You've played all available words!</h3>
          <% end %>
          <div class="row">
            <div class="col-sm-4">
              <strong>Games played:</strong>
              <%= @user_games_count %>
            </div>

            <div class="col-sm-4">
              <strong>Games won:</strong>
              <%= @user_wins_count %>
            </div>

            <div class="col-sm-4">
              <strong>Success ratio:</strong>
              <%= @user_success_ratio %>%
            </div>
          </div>
      </div>


      <% if @user == current_user %>
        <div id="profile-history" class="well text-center">
            <div class="row">
              <div class="col-sm-12">
                <h2>Games Played</h2>
                <table>
                  <thead>
                    <tr>
                      <th>Timestamp</th>
                      <th>Secret word</th>
                      <th>Letters guessed</th>
                      <th>Game outcome</th>
                    </tr>
                  </thead>

                  <tbody>
                  <% @user_games.each_with_index { |game, ind| %>
                    <tr>
                        <td><%= game.created_at %></td>
                        <td><%= game.secret_word %></td>
                        <td><%= game.letters_guessed %></td>
                        <td class="text-center">
                          <% if game.outcome == 0 %>
                          <span class="lost-game">LOST</span>
                          <% elsif game.outcome == 1 %>
                          <span class="won-game">WON</span>
                          <% end %>
                        </td>
                    </tr>
                  <% } %>
                  </tbody>
                </table>
              </div>
            </div>

        </div>
      <% end %>
    <% end %>

    <% if @user == current_user %>
      <div id="profile-details" class="well text-center">
        <div class="row">
          <div class="col-sm-12">
            <h2>Profile Details</h2>
          </div>
        </div>
        <div class="row">
          <div class="col-xs-4">
            <strong>Name:</strong>
            <%= @user.name %>
          </div>
          <div class="col-xs-4">
            <strong>Email:</strong>
            <%= @user.email %>
          </div>
          <div class="col-xs-4">
            <%= link_to 'Edit', edit_user_path(@user) %>
          </div>
        </div>
      </div>
    <% end %>


    <% if (@user == current_user) && !(@user_has_more_words_to_play.blank?) %>
      <div id="profile-newgame" class="text-center">
        <%= link_to "New Game", new_user_game_path(user_id: current_user.id), class: "btn btn-success" if user_signed_in? %>
      </div>
    <% end %>
  </div>
</div>