config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'static_pages/about'

  resources :users do
    resources :games
  end

#  resources :games
#  resources :users

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html


  root 'users#index'


end

app/models/game.rb
class Game < ApplicationRecord
  belongs_to :user
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_action :set_game, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  before_action :only_current_user
  before_action :user_needs_name

  # GET /games
  # GET /games.json
  def index
    @games = Game.all
  end

  # GET /games/1
  # GET /games/1.json
  def show
    @user = User.find( params[:user_id] )
    @game = @user.games.find( params[:id] )
    gallows_calc
  end

  # GET /games/new
  def new
    @game = Game.new

    # Find a new secret word that the user hasnt played yet
    @all_words = Word.pluck(:word)

    @user = User.find(params[:user_id])
    @user_games_words = @user.games.pluck(:secret_word)

    @all_words.each { |w|
      if !( @user_games_words.include? w )
        @new_secret_word = w
        break
      end
    }

    if @new_secret_word.blank?
        redirect_to user_path( params[:user_id] )
    end

  end

  # GET /games/1/edit
  def edit
    @user = User.find( params[:user_id] )
    @game = @user.games.find( params[:id] )
    gallows_calc
  end

  # POST /games
  # POST /games.json
  def create
    # Get the current user
    @user = User.find( params[:user_id] )

    # Find a new secret word that the user hasnt played yet
    @all_words = Word.pluck(:word)
    @user_games_words = @user.games.pluck(:secret_word)
    @all_words.each { |w|
      if !( @user_games_words.include? w )
        @new_secret_word = w
        break
      end
    }

    @game = Game.new
    @game.user_id = params[:user_id]
    @game.secret_word = @new_secret_word

    # Process guesses
    @new_letter_guess = ''
    @guess_multi_letters = ''
    ("a".."z").each { |letter|
      @game.letters_guessed = params["guessed_letter_" + letter] if !( params["guessed_letter_" + letter].blank? )
    }
    if ( @game.letters_guessed.blank? )
      if !( params[:guessed_multi_letters].blank? )
        @game.letters_guessed = params[:guess_multi_letters].upcase.gsub(/[^A-Z]/, '').split("").uniq.join("")
        check_letter_guesses
      elsif !( params[:guess_whole_word].blank? )
        @guess_whole_word = params[:guess_whole_word].downcase
        # Guessing the whole word on the 1st try
        @game.letters_guessed = ""
        if @guess_whole_word == @game.secret_word
          @game.outcome = 1
        else
          @game.outcome = 0
        end
      end
    end

    if @game.save
      if ( (@game.outcome == 1) || (@game.outcome == 0) )
        # If the game is over
        flash[:notice] = "You won!" if @game.outcome == 1
        flash[:alert] = "You lost!" if @game.outcome == 0
        redirect_to user_game_path( params[:user_id], @game.id )
      else
        # If the game is not over yet
        redirect_to edit_user_game_path( params[:user_id], @game.id )
      end
    else
      flash[:alert] = "Something went wrong. Let's try again."
      render action: :new
    end

    #respond_to do |format|
    #  if @game.save
    #    format.html { redirect_to @game, notice: 'Game was successfully created.' }
    #    format.json { render :show, status: :created, location: @game }
    #  else
    #    format.html { render :new }
    #    format.json { render json: @game.errors, status: :unprocessable_entity }
    #  end
    #end
  end

  # PATCH/PUT /games/1
  # PATCH/PUT /games/1.json
  def update

    @user = User.find( params[:user_id] )
    @game = @user.games.find( params[:id] )

    # Process guesses
    @new_letter_guess = ''
    @guess_multi_letters = ''
    ("a".."z").each { |letter|
      @new_letter_guess = params["guessed_letter_" + letter] if !( params["guessed_letter_" + letter].blank? )
    }
    if ( @new_letter_guess.blank? )
      if !( params[:guessed_multi_letters].blank? )
        @guess_multi_letters = params[:guess_multi_letters].upcase.gsub(/[^A-Z]/, '')
      elsif !( params[:guess_whole_word].blank? )
        @guess_whole_word = params[:guess_whole_word].downcase
        # Guessing the whole word
        if @guess_whole_word == @game.secret_word
          @game.outcome = 1
        else
          @game.outcome = 0
        end
      end
    end

    if !( (@game.outcome == 1) || (@game.outcome == 0) )
      # Calculate new game outcome (0, 1, or nil)
      @game.letters_guessed = '' if @game.letters_guessed.nil?
      @game.letters_guessed = @game.letters_guessed + @new_letter_guess + @guess_multi_letters
      # Remove duplicate guessed letters
      @game.letters_guessed = @game.letters_guessed.split("").uniq.join("")
      check_letter_guesses
    end

    if @game.update_attributes(:outcome => @game.outcome, :letters_guessed => @game.letters_guessed)
      if ( (@game.outcome == 1) || (@game.outcome == 0) )
        # If the game is over
        flash[:notice] = "You won!" if @game.outcome == 1
        flash[:alert] = "You lost!" if @game.outcome == 0
        redirect_to user_game_path( params[:user_id], @game.id )
      else
        # If the game is not over yet
        redirect_to edit_user_game_path( params[:user_id], @game.id )
      end
    else
      flash[:alert] = "Something went wrong. Let's try again."
      render action: :edit
    end

    #respond_to do |format|
    #  if @game.update(game_params)
    #    format.html { redirect_to @game, notice: 'Game was successfully updated.' }
    #    format.json { render :show, status: :ok, location: @game }
    #  else
    #    format.html { render :edit }
    #    format.json { render json: @game.errors, status: :unprocessable_entity }
    #  end
    #end
  end

  # DELETE /games/1
  # DELETE /games/1.json
  def destroy
    @game.destroy
    respond_to do |format|
      format.html { redirect_to games_url, notice: 'Game was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_game
      @game = Game.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def game_params
      params.permit(:user_id, :guessed_letter_a, :guessed_letter_b,
      :guessed_letter_c, :guessed_letter_d,
      :guessed_letter_e, :guessed_letter_f,
      :guessed_letter_g, :guessed_letter_h,
      :guessed_letter_i, :guessed_letter_j,
      :guessed_letter_k, :guessed_letter_l,
      :guessed_letter_m, :guessed_letter_n,
      :guessed_letter_o, :guessed_letter_p,
      :guessed_letter_q, :guessed_letter_r,
      :guessed_letter_s, :guessed_letter_t,
      :guessed_letter_u, :guessed_letter_v,
      :guessed_letter_w, :guessed_letter_x,
      :guessed_letter_y, :guessed_letter_z,
      :guess_multi_letters, :guessed_multi_letters,
      :guess_whole_word, :guessed_whole_word)
    end

    def only_current_user
      @user = User.find( params[:user_id] )
      redirect_to(root_url) unless @user == current_user
    end

    def user_needs_name
      redirect_to(edit_user_path(current_user)) if current_user.name.blank?
    end

    def gallows_calc
      @game.letters_guessed = '' if @game.letters_guessed.nil?
      @lguesses = @game.letters_guessed.downcase

      # Calculate wrong guesses count for gallows diagram
      @correct_guesses_num = 0
      @game.secret_word.split('').each_with_index { |ch, ind|
        if !( @game.secret_word.split('').take(ind).include? ch )
          if @lguesses.include? ch
            @correct_guesses_num = @correct_guesses_num + 1
          end
        end
      }
      @wrong_guesses_num = @lguesses.length - @correct_guesses_num
    end

    def check_letter_guesses
      @lguesses = @game.letters_guessed.downcase
      @correct_guesses_num = 0
      @secret_word_unique_letters_count = 0
      @game.secret_word.split('').each_with_index { |ch, ind|
        if !( @game.secret_word.split('').take(ind).include? ch )
          if @lguesses.include? ch
            @correct_guesses_num = @correct_guesses_num + 1
          end
          @secret_word_unique_letters_count = @secret_word_unique_letters_count + 1
        end
      }

      # Did user guess all letters of secret word?
      if @correct_guesses_num == @secret_word_unique_letters_count
        # Won game, b/c user guessed all letters of secret word
        @game.outcome = 1
      else
        # Are there 10 wrong guesses?
        @wrong_guesses_num = @lguesses.length - @correct_guesses_num
        if @wrong_guesses_num >= 10
          # Lost game, b/c there are 10 wrong guesses
          @game.outcome = 0
        else
          # Neither lost nor won yet
          @game.outcome = nil
        end
      end
    end
end

app/helpers/games_helper.rb
module GamesHelper
end

app/views/games/_edit_form.html.erb
<%= form_for game, url: user_game_path do |f| %>
  <% if game.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(game.errors.count, "error") %> prohibited this game from being saved:</h2>

      <ul>
      <% game.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div id="guess-letters">
    <h2> Pick A Letter!</h2>
    <% ("A".."Z").each { |alpha| %>
      <% if @game.letters_guessed.include? alpha %>
        <%= submit_tag alpha, name: 'guessed_letter_' + alpha.downcase, class: "btn btn-primary", disabled: true %>
      <% else %>
        <%= submit_tag alpha, name: 'guessed_letter_' + alpha.downcase, class: "btn btn-primary" %>
      <% end %>
    <% } %>
  </div>
  <hr>
  <div id="guess-multi-letters" class="text-center">
    <h2> Guess a bunch of letters at once!</h2>
    <%= text_field_tag 'guess_multi_letters', nil, placeholder: 'Enter your guesses here' %>
    <div class="actions">
      <%= f.submit "Submit", name: 'guessed_multi_letters', class: "btn btn-warning" %>
    </div>
  </div>
  <hr>
  <div id="guess-whole-word" class="text-center">
    <h2> Guess the whole word!</h2>
    <%= text_field_tag 'guess_whole_word', nil, placeholder: 'Enter your guess here' %>
    <div class="actions">
      <%= f.submit "Submit", name: 'guessed_whole_word', class: "btn btn-warning" %>
    </div>
  </div>

<% end %>

app/views/games/_form.html.erb
<%= form_for game, url: user_games_path do |f| %>
  <% if game.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(game.errors.count, "error") %> prohibited this game from being saved:</h2>

      <ul>
      <% game.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div id="guess-letters">
    <h2> Pick A Letter!</h2>
    <% ("A".."Z").each { |alpha| %>
      <%= submit_tag alpha, name: 'guessed_letter_' + alpha.downcase, class: "btn btn-primary" %>
    <% } %>
  </div>
  <hr>
  <div id="guess-multi-letters" class="text-center">
    <h2> Guess a bunch of letters at once!</h2>
    <%= text_field_tag 'guess_multi_letters', nil, placeholder: 'Enter your guesses here' %>
    <div class="actions">
      <%= f.submit "Submit", name: 'guessed_multi_letters', class: "btn btn-warning" %>
    </div>
  </div>
  <hr>
  <div id="guess-whole-word" class="text-center">
    <h2> Guess the whole word!</h2>
    <%= text_field_tag 'guess_whole_word', nil, placeholder: 'Enter your guess here' %>
    <div class="actions">
      <%= f.submit "Submit", name: 'guessed_whole_word', class: "btn btn-warning" %>
    </div>
  </div>

<% end %>

app/views/games/edit.html.erb
<div class="row">
  <div class="col-sm-4 col-sm-offset-1">
    <div class="well">
      <div id="gallows-container" class="text-center">
        <% case @wrong_guesses_num %>
        <%  when 0 %>
          <%= image_tag("gallows_0.png") %>
        <%  when 1 %>
          <%= image_tag("gallows_1.png") %>
        <%  when 2 %>
          <%= image_tag("gallows_2.png") %>
        <%  when 3 %>
          <%= image_tag("gallows_3.png") %>
        <%  when 4 %>
          <%= image_tag("gallows_4.png") %>
        <%  when 5 %>
          <%= image_tag("gallows_5.png") %>
        <%  when 6 %>
          <%= image_tag("gallows_6.png") %>
        <%  when 7 %>
          <%= image_tag("gallows_7.png") %>
        <%  when 8 %>
          <%= image_tag("gallows_8.png") %>
        <%  when 9 %>
          <%= image_tag("gallows_9.png") %>
        <%  when 10 %>
          <%= image_tag("gallows_10.png") %>
        <% end %>
      </div>
      <div id="secret-word-container" class="text-center">
        <br>
        <% @game.secret_word.split('').each { |secret_letter| %>
          <% if @game.letters_guessed.downcase.include? secret_letter %>
            <span class="shown-letter"><%= secret_letter.upcase %></span>
          <% else %>
            <span class="hidden-letter">__</span>
          <% end %>
        <% } %>
      </div>
    </div>
  </div>
  <div class="col-sm-4 col-sm-offset-1">
    <div class="well">
      <%= render 'edit_form', game: @game %>
    </div>
  </div>
</div>

app/views/games/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Games</h1>

<table>
  <thead>
    <tr>
      <th>Secret word</th>
      <th>User</th>
      <th>Outcome</th>
      <th>Letters guessed</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @games.each do |game| %>
      <tr>
        <td><%= game.secret_word %></td>
        <td><%= game.user_id %></td>
        <td><%= game.outcome %></td>
        <td><%= game.letters_guessed %></td>
        <td><%= link_to 'Show', game %></td>
        <td><%= link_to 'Edit', edit_game_path(game) %></td>
        <td><%= link_to 'Destroy', game, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Game', new_game_path %>

app/views/games/new.html.erb
<div class="row">
  <div class="col-sm-4 col-sm-offset-1">
    <div class="well">
      <div id="gallows-container" class="text-center">
        <%= image_tag("gallows_0.png") %>
      </div>
      <div id="secret-word-container" class="text-center">
        <br>
        <% @new_secret_word.split('').each { |secret_letter| %>
          <span class="hidden-letter">__</span>
        <% } %>
      </div>
    </div>
  </div>
  <div class="col-sm-4 col-sm-offset-1">
    <div class="well">
      <%= render 'form', game: @game %>
    </div>
  </div>
</div>

app/views/games/show.html.erb
<div class="row">
  <div class="col-sm-4 col-sm-offset-1">
    <div class="well">
      <div id="gallows-container" class="text-center">
        <% if @game.outcome == 0 %>
          <%= image_tag("gallows_10.png") %>
        <% else %>
          <% case @wrong_guesses_num %>
          <%  when 0 %>
            <%= image_tag("gallows_0.png") %>
          <%  when 1 %>
            <%= image_tag("gallows_1.png") %>
          <%  when 2 %>
            <%= image_tag("gallows_2.png") %>
          <%  when 3 %>
            <%= image_tag("gallows_3.png") %>
          <%  when 4 %>
            <%= image_tag("gallows_4.png") %>
          <%  when 5 %>
            <%= image_tag("gallows_5.png") %>
          <%  when 6 %>
            <%= image_tag("gallows_6.png") %>
          <%  when 7 %>
            <%= image_tag("gallows_7.png") %>
          <%  when 8 %>
            <%= image_tag("gallows_8.png") %>
          <%  when 9 %>
            <%= image_tag("gallows_9.png") %>
          <%  when 10 %>
            <%= image_tag("gallows_10.png") %>
          <% end %>
        <% end %>
      </div>
      <div id="secret-word-container" class="text-center">
        <br>
        <% @game.secret_word.split('').each { |secret_letter| %>
          <% if ( (@game.letters_guessed.downcase.include? secret_letter) || (@game.outcome == 1) ) %>
            <span class="shown-letter guessed-letter"><%= secret_letter.upcase %></span>
          <% else %>
            <span class="missed-letter"><%= secret_letter.upcase %></span>
          <% end %>
        <% } %>
      </div>
    </div>
  </div>
  <div class="col-sm-4 col-sm-offset-1">
    <div id="gameover-board" class="well text-center">
      <% if @game.outcome == 0 %>
        <h2 id="lost-game-message">You lost!</h2>
      <% elsif @game.outcome == 1 %>
        <h2 id="won-game-message">You won!</h2>
      <% end %>
      <hr>
      <%= link_to "New Game", new_user_game_path(user_id: current_user.id), class: "btn btn-success" if user_signed_in? %>
    </div>
  </div>
</div>