config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'static_pages/about'

  resources :users do
    resources :games
  end

#  resources :games
#  resources :users

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html


  root 'users#index'


end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Hangman game</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <meta name="viewport" content="width=device-width,initial-scale=1">
  </head>

  <body>

    <nav class="navbar navbar-default navbar-static-top" role="navigation">
      <div class='container'>
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#main-nav-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <%= link_to "/", class: "navbar-brand" do %>
            <i class="fa fa-group"></i>
            HANGMAN
          <% end %>
        </div>
        <div class="collapse navbar-collapse" id="main-nav-collapse">
          <div class="nav navbar-nav navbar-right">
            <% if user_signed_in? %>
              <%= link_to "Log Out", destroy_user_session_path, method: :delete, class: "btn btn-default navbar-btn" %>
            <% else %>
              <%= link_to "Log In", new_user_session_path, class: "btn btn-default navbar-btn" %>
              <%= link_to "Sign Up", new_user_registration_path, class: "btn btn-default navbar-btn" %>
            <% end %>
          </div>

          <ul class="nav navbar-nav navbar-right">
            <li><%= link_to "Play", new_user_game_path(user_id: current_user.id) if user_signed_in? %></li>
            <li><%= link_to "Leaderboard", "/" if user_signed_in? %></li>
            <li><%= link_to "Profile", user_path(id: current_user.id) if user_signed_in? %></li>
            <li><%= link_to "About", "/static_pages/about" %></li>
          </ul>
        </div><!-- /.navbar-collapse -->
      </div>
    </nav>


    <div class="container">
      <%= yield %>
    </div>

  </body>
</html>